// Generated by CoffeeScript 1.3.3
(function() {
  var poll, toWidth;

  toWidth = function(percent) {
    return 'width: ' + (percent * 100).round + 'px';
  };

  poll = function() {
    var goal;
    goal = 1000000 / 11.17000;
    console.log("Polling...");
    return $.getJSON("/status.json", function(data) {
      var block, prevent, release;
      block = data['most_recent_block'];
      prevent = data['prevent'] / goal;
      release = data['release'] / goal;
      $('#prevent').attr('style', toWidth(prevent));
      return $('#release').attr('style', toWidth(release));
    });
  };

  $(document).ready(function() {
    return window.setInterval(poll, 10000);
  });

}).call(this);
